#!/bin/sh
_microfetch() {
  local dotbin="$HOME/.dotfiles/bin"

  local arch=""
  case "$(uname -m)" in
    x86_64)  arch="linux64-static" ;;
    aarch64) arch="linux-arm64" ;;
    *)       echo "error: unknown architecture"; return ;;
  esac

  local rel="https://api.github.com/repos/zyedidia/micro/releases/latest"
  local ver=`curl -s "${rel}" | grep '"tag_name":' | sed -E 's/.*"([^"]+)".*/\1/' | tr -d 'v'`
  local pkg="https://github.com/zyedidia/micro/releases/download/v${ver}/micro-${ver}-${arch}.tar.gz"

  mkdir _micropkg && \
  curl -sL  "${pkg}" | tar xz -C ./_micropkg && \
  mv -f ./_micropkg/micro-${ver}/micro ${dotbin}/micro && \
  chmod 755 ${dotbin}/micro && \
  rm -rf _micropkg && \
  echo "created ${dotbin}/micro (v${ver})"

  mkdir -p $HOME/.config/micro && \
  curl -sL  https://raw.githubusercontent.com/skyfalconua/dotfiles/main/configs/base/micro/settings.json > $HOME/.config/micro/settings.json
  echo "created $HOME/.config/micro/settings.json"
}
_microfetch; unset _microfetch
