#!/bin/sh
_brewsetup() {
  brew install \
    firefox ghostty zed keepassxc pinta macpacker \
    font-cascadia-code-nf container podman pstree \
    tmux wget mc htop ncdu micro fzf ripgrep jq   \
    yazi carapace zoxide git-delta gitui tree bat \
    deno aria2 entr xz pixz pigz sevenzip
    # \ visual-studio-code antigravity
    # \ claude-code gemini-cli kiro-cli codex
}
_brewsetup; unset _brewsetup
