#!/bin/sh
_carapacefetch() {
  local dotbin="$HOME/.dotfiles/bin"

  local arch=""
  case "$(uname -m)" in
    x86_64)  arch="amd64" ;;
    aarch64) arch="arm64" ;;
    *)       echo "error: unknown architecture"; return ;;
  esac

  local rel="https://api.github.com/repos/carapace-sh/carapace-bin/releases/latest"
  local ver=`curl -s "${rel}" | grep '"tag_name":' | sed -E 's/.*"([^"]+)".*/\1/' | tr -d 'v'`
  local pkgname="carapace-bin_${ver}_linux_${arch}"
  local pkgurl="https://github.com/carapace-sh/carapace-bin/releases/download/v${ver}/${pkgname}.tar.gz"

  mkdir _carapace && \
  curl -sL  "${pkgurl}" | tar xz -C _carapace && \
  mv -f ./_carapace/carapace ${dotbin}/carapace && \
  chmod 755 ${dotbin}/carapace && \
  rm -rf _carapace && \
  echo "created ${dotbin}/carapace (v${ver})"
}
_carapacefetch; unset _carapacefetch
