#!/bin/sh
_gituifetch() {
  local dotbin="$HOME/.dotfiles/bin"

  local pkgname=""
  local exe=""
  case "$(uname -s)" in
    Linux)        pkgname="gitui-linux-$(uname -m)" ;;
    MINGW*|MSYS*) pkgname="gitui-win" exe=".exe" ;;
    *)            echo "error: unsupported os"; return ;;
  esac

  local rel="https://api.github.com/repos/gitui-org/gitui/releases/latest"
  local ver=`curl -s "${rel}" | grep '"tag_name":' | sed -E 's/.*"([^"]+)".*/\1/' | tr -d 'v'`
  local pkgurl="https://github.com/gitui-org/gitui/releases/download/v${ver}/${pkgname}.tar.gz"

  mkdir _gitui && \
  curl -sL "${pkgurl}" | tar xz -C _gitui && \
  mv -f ./_gitui/gitui${exe} ${dotbin}/gitui${exe} && \
  chmod 755 ${dotbin}/gitui${exe} && \
  rm -rf _gitui && \
  echo "created ${dotbin}/gitui (v${ver})"
}
_gituifetch; unset _gituifetch
