#!/bin/sh
_helixfetch() {
  local dotbin="$HOME/.dotfiles/bin"

  local rel="https://api.github.com/repos/helix-editor/helix/releases/latest"
  local ver=`curl -s "${rel}" | grep '"tag_name":' | sed -E 's/.*"([^"]+)".*/\1/' | tr -d 'v'`
  local arch=$(uname -m)
  local pkgurl="https://github.com/helix-editor/helix/releases/download/${ver}/helix-${ver}-${arch}-linux.tar.xz"

  mkdir -p /opt && \
  cd /opt && \
  curl -sL  "${pkgurl}" | tar xJ -C . && \
  mv "helix-${ver}-${arch}-linux" "helix" && \
  chmod 755 /opt/helix/hx && \
  ln -sfv /opt/helix/hx ${dotbin}/hx && \
  echo "created ${dotbin}/hx (v${ver})" \
  cd

  local dotfiles="https://raw.githubusercontent.com/skyfalconua/dotfiles/main"

  mkdir -p "$HOME/.config/helix" && \
  curl -sL  "${dotfiles}/configs/other/helix/config.toml" > "$HOME/.config/helix/config.toml" && \
  echo "created $HOME/.config/helix/config.toml"
}
_helixfetch; unset _helixfetch
