#!/bin/sh
_microfetch() {
  local dotbin="$HOME/.dotfiles/bin"

  local rel="https://skyfalconua.github.io/pkgs/micro/VERSION"
  local ver=`curl -sL "${rel}" | xargs`
  local pkg="https://skyfalconua.github.io/pkgs/micro/micro-${ver}-$(uname -m)"

  curl -sL  "${pkg}" > "${dotbin}/micro" && \
  chmod 755 "${dotbin}/micro" && \
  echo "created ${dotbin}/micro (v${ver})"
}
_microfetch; unset _microfetch
