#!/bin/sh
_systemdtuifetch() {
  local dotbin="$HOME/.dotfiles/bin"

  local rel="https://api.github.com/repos/rgwood/systemctl-tui/releases/latest"
  local ver=`curl -s "${rel}" | grep '"tag_name":' | sed -E 's/.*"([^"]+)".*/\1/' | tr -d 'v'`
  local pkgname="systemctl-tui-$(uname -m)-unknown-linux-musl"
  local pkgurl="https://github.com/rgwood/systemctl-tui/releases/download/v${ver}/${pkgname}.tar.gz"

  mkdir _systemdtui && \
  curl -sL  "${pkgurl}" | tar xz -C _systemdtui && \
  mv -f ./_systemdtui/systemctl-tui ${dotbin}/systemctl-tui && \
  chmod 755 ${dotbin}/systemctl-tui && \
  rm -rf _systemdtui && \
  echo "created ${dotbin}/systemctl-tui (v${ver})"
}
_systemdtuifetch; unset _systemdtuifetch
