#!/bin/sh
_yazifetch() {
  local rel="https://raw.githubusercontent.com/skyfalconua/pkgs/refs/heads/main/yazi/VERSION"
  local ver=`curl -s "${rel}" | xargs`
  local bin=""
  local exe=""

  case "$(uname -s)" in
    Linux)        bin="unknown-linux-musl" ;;
    MINGW*|MSYS*) bin="pc-windows-msvc" exe=".exe" ;;
    *)            echo "error: unsupported os"; return ;;
  esac

  # require root for linux
  if [ -z "$exe" ] && [ ! `whoami` = "root" ]; then
    echo "error: must be run as root"; return
  fi

  local pkg="https://skyfalconua.github.io/pkgs/yazi/yazi-${ver}-$(uname -m)-${bin}${exe}"

  curl -sL  "${pkg}" > "/usr/bin/yazi${exe}" && \
  chmod 755 "/usr/bin/yazi${exe}" && \
  echo "created /usr/bin/yazi${exe} (v${ver})"
}
_yazifetch; unset _yazifetch
