#!/bin/sh
_yazifetch() {
  local dotbin="$HOME/.dotfiles/bin"

  local bin=""
  local exe=""
  case "$(uname -s)" in
    Linux)        bin="unknown-linux-musl" ;;
    MINGW*|MSYS*) bin="pc-windows-msvc" exe=".exe" ;;
    *)            echo "error: unsupported os"; return ;;
  esac

  # require root for linux
  if [ -z "$exe" ] && [ ! `whoami` = "root" ]; then
    echo "error: must be run as root"; return
  fi

  local pkg="https://skyfalconua.github.io/pkgs/yazi/yazi-${ver}-$(uname -m)-${bin}${exe}"

  curl -sL  "${pkg}" > "${dotbin}/yazi${exe}" && \
  chmod 755 "${dotbin}/yazi${exe}" && \
  echo "created ${dotbin}/yazi${exe} (v${ver})"
}
_yazifetch; unset _yazifetch
