#!/bin/sh
_zoxidefetch() {
  local dotbin="$HOME/.dotfiles/bin"

  local rel="https://api.github.com/repos/ajeetdsouza/zoxide/releases/latest"
  local ver=`curl -s "${rel}" | grep '"tag_name":' | sed -E 's/.*"([^"]+)".*/\1/' | tr -d 'v'`
  local pkgname="zoxide-${ver}-$(uname -m)-unknown-linux-musl"
  local pkgurl="https://github.com/ajeetdsouza/zoxide/releases/download/v${ver}/${pkgname}.tar.gz"

  mkdir _zoxide && \
  curl -sL  "${pkgurl}" | tar xz -C _zoxide && \
  mv -f ./_zoxide/zoxide ${dotbin}/zoxide && \
  chmod 755 ${dotbin}/zoxide && \
  rm -rf _zoxide && \
  echo "created ${dotbin}/zoxide (v${ver})"
}
_zoxidefetch; unset _zoxidefetch
